package com.example.ProjetoGerenciadorDeTarefa.view;


import com.example.ProjetoGerenciadorDeTarefa.Model.Usuario;
import com.example.ProjetoGerenciadorDeTarefa.controller.AutenticacaoController;
import javax.swing.*;

public class TelaLogin extends javax.swing.JFrame {

    private JTextField txtUsuario;
    private JPasswordField txtSenha;
    private JButton btnLogin;
    private Object com;

    public TelaLogin() {

        setTitle("Login");
        setSize(350,200);
        setLayout(null);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        JLabel lblUsuario = new JLabel("Usuário:");
        lblUsuario.setBounds(30,30,80,25);
        add(lblUsuario);

        txtUsuario = new JTextField();
        txtUsuario.setBounds(100,30,180,25);
        add(txtUsuario);

        JLabel lblSenha = new JLabel("Senha:");
        lblSenha.setBounds(30,70,80,25);
        add(lblSenha);

        txtSenha = new JPasswordField();
        txtSenha.setBounds(100,70,180,25);
        add(txtSenha);

        btnLogin = new JButton("Login");
        btnLogin.setBounds(110,110,100,30);
        add(btnLogin);

        btnLogin.addActionListener(e -> fazerLogin());
    }

    private void fazerLogin() {

    String nome = txtUsuario.getText();
    String senha = new String(txtSenha.getPassword());

    AutenticacaoController controller = new AutenticacaoController();

    Usuario usuario = controller.autenticar(nome, senha);

    if (usuario != null) {

        JOptionPane.showMessageDialog(this, "Login realizado!");

        MenuPrincipalView menu = new MenuPrincipalView(usuario);
        menu.setVisible(true);

        dispose();

    } else {

        JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos");

    }

    
    } /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {

            new TelaLogin().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
